---
- name: Include retrieve tasks
  ansible.builtin.include_tasks: includes/retrieve.yaml
  when: data_store['scm']['origin'] is defined
  run_once: true

- name: Include retrieve tasks
  ansible.builtin.set_fact:
    network_backup_path: "{{  data_store.scm.origin.url.split('/')[-1] }}"
  when:
    - data_store['scm']['origin'] is defined
    - network_backup_path is not defined

- name: Set detection path when data store is remote
  ansible.builtin.set_fact:
    src_network_backup_path: "{{ role_path }}/../../{{ network_backup_path }}/{{ inventory_hostname }}.txt"
  when: data_store['scm']['origin'] is defined

- name: Include retrieve tasks
  ansible.builtin.set_fact:
    src_network_backup_path: "{{  data_store.scm.origin.url.split('/')[-1] }}"
  when: data_store['scm']['origin'] is defined

