---
- name: Set supported platform list
  ansible.builtin.set_fact:
    supported_cli_restore:
      - "eos"
    supported_plugin_restore:
      - "nxos"
      - "iosxr"
      - "ios"
      - "junos"
    network_os: "{{ ansible_network_os.split('.')[2] }}"

- name: Invoke restore
  ansible.builtin.include_tasks: "includes/cli_restore.yaml"
  when: network_os not in supported_cli_restore

- name: Invoke cli specific backup task
  ansible.builtin.include_tasks: "includes/cli_restore_config.yaml"
  when: network_os not in supported_plugin_restore
