---
- name: Set Timestamp
  ansible.builtin.set_fact:
    time: "{{ lookup('pipe','date \"+%Y-%m-%d-%H-%M\"') }}"
  run_once: true

- name: Create default tag
  ansible.builtin.set_fact:
    default_tag:
      annotation: "{{ time }}"
      message: "backup_on: {{ time }}"

- name: Set default tag
  ansible.builtin.set_fact:
    default_tag: "{}"
  when:
    - tag is defined
    - tag  == "default"

- name: Publish the changes with tag
  ansible.scm.git_publish:
    path: "{{ network_backup_path }}"
    token: "{{ data_store['scm']['origin']['token'] | d(None) }}"
    user: "{{ data_store['scm']['origin']['user'] | d({}) }}"
    tag: "{{ tag }}"
    timeout: 120
  when: tag is defined

- name: Publish the changes
  ansible.scm.git_publish:
    path: "{{ network_backup_path }}"
    token: "{{ data_store['scm']['origin']['token'] | d(None) }}"
    user: "{{ data_store['scm']['origin']['user'] | d({}) }}"
    timeout: 120
  when: tag is not defined
