---
- name: Set IOSXR directory - content specific facts
  ansible.builtin.set_fact:
    dest_dir: "/misc/"
    appliance_dir: "/misc/"

- name: Parse free space information
  ansible.utils.cli_parse:
    command: "dir /all | include free"
    parser:
      name: ansible.netcommon.content_templates
      template_path: "{{ tmplt_path }}/{{ network_os }}.yaml"
    set_fact: appliance_dir_data

- name: Include task to compare file size with free space
  ansible.builtin.include_tasks: "includes/common/healthcheck_common.yaml"
