---
- name: Create Full Backup Play
  hosts: rtr1
  gather_facts: false
  vars:
    GH_REPO: "https://github.com/rohitthakur2590/network_automation_backups"
  tasks:
    - name: Create time stamp for play
      ansible.builtin.set_fact:
        datetime: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"
      # delegate_to: localhost
      # delegate_facts: true
      # run_once: true

    - name: Perform pre-run checks
      ansible.builtin.include_tasks:
        file: ./pre_remote_validation.yaml

    - name: Network Backup and Resource Manager
      ansible.builtin.include_role:
        name: network.backup.backup
      vars:
        operation: backup
        data_store:
          scm:
            origin:
              url: "{{ GH_REPO }}"
              token: "{{ GH_TOKEN }}"
              user:
                name: rohitthakur2590
                email: rohitthakur2590@outlook.com
          backup_file_name: "{{ datetime }}"
